spring:
  datasource:
    url: jdbc:h2:mem:tasks;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
      defer-datasource-initialization: true
  flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration
